package billund.reference;

import net.minecraftforge.fml.common.ModMetadata;

import java.util.Arrays;

public class MetaData
{
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = "Plastic building blocks for Minecraft!";
        metadata.url = "https://github.com/way2muchnoise/Billund-Port";
        metadata.version = Reference.VERSION_FULL;
        metadata.authorList = Arrays.asList("way2muchnoise");
        metadata.credits = "Credit for the original mod goes to Dan200";
        metadata.autogenerated = false;
        return metadata;
    }
}
